In [1]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset to a pandas DataFrame
news_dataset = pd.read_csv('train.csv')

In [3]:
# print the first 5 rows of the dataframe
news_dataset.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
# counting the number of missing values in the dataset
news_dataset.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [5]:
news_dataset.shape

(20800, 5)

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
# printing the stopwords in English
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [8]:
# replacing the null values with empty string
news_dataset = news_dataset.fillna('')

In [16]:
# merging the author name and news title
news_dataset['content'] = news_dataset['title']

In [17]:
print(news_dataset['content'])

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                        Why the Truth Might Get You Fired
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799                            What Keeps the F-35 Alive
Name: content, Length: 20800, dtype: object


In [18]:
port_stem = PorterStemmer()

In [19]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [20]:
news_dataset['content'] = news_dataset['content'].apply(stemming)

In [21]:
print(news_dataset['content'])

0        hous dem aid even see comey letter jason chaff...
1          flynn hillari clinton big woman campu breitbart
2                                     truth might get fire
3                 civilian kill singl us airstrik identifi
4        iranian woman jail fiction unpublish stori wom...
                               ...                        
20795            rapper trump poster child white supremaci
20796      n f l playoff schedul matchup odd new york time
20797    maci said receiv takeov approach hudson bay ne...
20798             nato russia hold parallel exercis balkan
20799                                          keep f aliv
Name: content, Length: 20800, dtype: object


In [22]:
#separating the data and label
X = news_dataset['content'].values
Y = news_dataset['label'].values

In [23]:
print(X)

['hous dem aid even see comey letter jason chaffetz tweet'
 'flynn hillari clinton big woman campu breitbart' 'truth might get fire'
 ... 'maci said receiv takeov approach hudson bay new york time'
 'nato russia hold parallel exercis balkan' 'keep f aliv']


In [24]:
print(Y)

[1 0 1 ... 0 1 1]


In [25]:
# converting the textual data to numerical data
vectorizer = TfidfVectorizer()
vectorizer.fit(X)

X = vectorizer.transform(X)

In [26]:
print(X)

  (0, 13610)	0.3204429041871619
  (0, 11663)	0.28865071055944214
  (0, 7472)	0.3286263634991149
  (0, 6751)	0.37807503658407626
  (0, 6143)	0.24709678286281997
  (0, 4394)	0.2624700707018907
  (0, 3340)	0.3043365499413147
  (0, 2578)	0.2776884546129286
  (0, 2165)	0.4135903166037093
  (0, 243)	0.3038505731698672
  (1, 14597)	0.4029069338022535
  (1, 5974)	0.255243301322185
  (1, 4874)	0.49350006801559954
  (1, 2444)	0.25583271340004526
  (1, 1946)	0.5127916215485694
  (1, 1650)	0.21311459271319796
  (1, 1313)	0.3938922297906677
  (2, 13543)	0.520272613528009
  (2, 8285)	0.5879029381082882
  (2, 5278)	0.41416349493213955
  (2, 4770)	0.460603020443823
  (3, 13947)	0.2910988442735044
  (3, 12016)	0.4595551330231538
  (3, 7080)	0.3129596268768328
  (3, 6271)	0.48520717569885846
  :	:
  (20796, 14760)	0.12072790494289075
  (20796, 13246)	0.11914995894745603
  (20796, 11529)	0.4694159922014375
  (20796, 9959)	0.4804399319541416
  (20796, 9158)	0.4804399319541416
  (20796, 8881)	0.11669800295

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify=Y, random_state=2)

In [28]:
model = LogisticRegression()

In [29]:
model.fit(X_train, Y_train)

LogisticRegression()

In [30]:
# accuracy score on the training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [31]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.9400240384615385


In [32]:
# accuracy score on the test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [33]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9298076923076923


In [34]:
from sklearn.linear_model import PassiveAggressiveClassifier
linear_clf = PassiveAggressiveClassifier()

In [35]:
linear_clf.fit(X_train, Y_train)
pred = linear_clf.predict(X_test)
score = accuracy_score(Y_test, pred)
print("accuracy:   %0.3f" % score)

accuracy:   0.921


In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
dt=DecisionTreeClassifier()
dt.fit(X_train,Y_train)

DecisionTreeClassifier()

In [38]:
y_pred = dt.predict(X_test)
test_data_accuracy = accuracy_score(y_pred, Y_test)

In [39]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9134615384615384


In [40]:
X_train_prediction = dt.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [41]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9134615384615384


In [42]:
dt=DecisionTreeClassifier(criterion="entropy", max_depth=100)
dt.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=100)

In [43]:
y_pred = dt.predict(X_test)
test_data_accuracy = accuracy_score(y_pred, Y_test)

In [44]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9276442307692307


In [45]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
clf=RandomForestClassifier(n_estimators=120)
clf.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=120)

In [47]:
y_pred=clf.predict(X_test)
test_data_accuracy = accuracy_score(y_pred, Y_test)

In [48]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9418269230769231


In [49]:
from sklearn.ensemble import GradientBoostingClassifier

In [50]:
gbc=GradientBoostingClassifier(random_state=10)
gbc.fit(X_train,Y_train)

GradientBoostingClassifier(random_state=10)

In [51]:
y_pred=gbc.predict(X_test)
test_data_accuracy = accuracy_score(y_pred, Y_test)

In [52]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9204326923076923


In [53]:
from sklearn.neighbors import KNeighborsClassifier

In [54]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=9)

In [55]:
y_pred = knn.predict(X_test)
test_data_accuracy = accuracy_score(y_pred, Y_test)

In [56]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.5072115384615384


In [57]:
from sklearn import svm

In [58]:
clf = svm.SVC(kernel='linear',C=5)
clf.fit(X_train, Y_train)

SVC(C=5, kernel='linear')

In [59]:
y_pred = clf.predict(X_test)
test_data_accuracy = accuracy_score(y_pred, Y_test)

In [60]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9302884615384616


In [61]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [62]:
classifier.fit(X_train, Y_train)
pred = classifier.predict(X_test)
score = accuracy_score(Y_test, pred)

In [63]:
print('Accuracy score of the test data : ', score)

Accuracy score of the test data :  0.8891826923076923


In [64]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, pred)

array([[1960,  117],
       [ 344, 1739]], dtype=int64)

In [59]:
from sklearn.model_selection import cross_val_score
cv_score=cross_val_score(classifier,X_train,Y_train,cv=10)

In [60]:
cv_score

array([0.95132212, 0.94411058, 0.95372596, 0.95552885, 0.95372596,
       0.95913462, 0.95853365, 0.94411058, 0.95612981, 0.94831731])

In [61]:
cv_score.mean()

0.9524639423076925

In [65]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
bag_model.fit(X_train, Y_train)
bag_model.oob_score_

0.9305288461538461

In [66]:
pred = bag_model.predict(X_test)
score = accuracy_score(Y_test, pred)

In [67]:
print('Accuracy score of the test data : ', score)

Accuracy score of the test data :  0.9338942307692307


In [67]:
bag_model = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
scores = cross_val_score(bag_model, X_train, Y_train, cv=5)
scores

array([0.99248798, 0.99459135, 0.99098558, 0.99399038, 0.9936899 ])

In [68]:
scores.mean()

0.9931490384615385

In [69]:
from sklearn.ensemble import RandomForestClassifier

scores = cross_val_score(RandomForestClassifier(n_estimators=50), X_train, Y_train, cv=5)
scores.mean()

0.9905649038461538

In [68]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators=50,
                         learning_rate=1)
model = abc.fit(X_train, Y_train)
y_pred = model.predict(X_test)
test_data_accuracy = accuracy_score(y_pred, Y_test)

In [69]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.9271634615384615
